---
- name: Un-deploying Apache Webserver
  hosts: webservers
  become: yes
  tasks:
    - name: Stop apache service
      service: name=apache2 state=stopped

    - name: Uninstalling apache
      apt:
        name: apache2
        state: absent
        purge: yes
        autoremove: yes
